# Generated by Django 6.0.3 on 2026-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
