# Generated by Django 6.0.3 on 2026-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
